# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import rnoc.models
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BCNOSS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object', models.CharField(max_length=50, verbose_name='\u0110\u1ed1i t\u01b0\u1ee3ng')),
                ('gio_mat', models.DateTimeField(verbose_name='Gi\u1edd m\u1ea5t')),
                ('gio_tot', models.DateTimeField(null=True, verbose_name='gi\u1edd t\u1ed1t', blank=True)),
                ('code_loi', models.IntegerField()),
                ('vnp_comment', models.CharField(max_length=500)),
                ('gio_canh_bao_ac', models.DateTimeField(null=True, verbose_name='gi\u1edd canh bao AC', blank=True)),
                ('tong_thoi_gian', models.IntegerField(null=True, verbose_name='t\u1ed5ng th\u1eddi gian', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BSCRNC',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=50)),
                ('HANG_SX', models.CharField(max_length=20, null=True, blank=True)),
                ('DIA_CHI', models.CharField(max_length=200, null=True, blank=True)),
                ('DIEN_THOAI', models.CharField(max_length=20, null=True, blank=True)),
                ('TINH_RNC_QUAN_LY', models.CharField(max_length=50, null=True, blank=True)),
                ('bsc_or_rnc', models.CharField(max_length=50)),
                ('so_luong_tram', models.IntegerField(null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BTSType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CaTruc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=30)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('is_duoc_tao_truoc', models.BooleanField(default=False, verbose_name='Kh\xf4ng cho ph\xe9p s\u1eeda field Name')),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_catruc_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CauHinh',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=50)),
                ('ghi_chu', models.CharField(max_length=300, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('datetime', models.DateTimeField(verbose_name='nh\u1eadp gi\u1edd', blank=True)),
                ('comment', models.CharField(max_length=2000, null=True, blank=True)),
                ('ngay_gio_tao', models.DateTimeField(verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=20)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, blank=True)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('is_duoc_tao_truoc', models.BooleanField(default=False, verbose_name='Kh\xf4ng cho ph\xe9p s\u1eeda field Name')),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('picture', models.CharField(max_length=200, null=True, blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_component_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_component_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DapAn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=500)),
                ('is_true_or_false', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiaBan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=50)),
                ('Name_khong_dau', models.CharField(unique=True, max_length=50, blank=True)),
                ('ky_hieu', models.CharField(max_length=50)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('so_luong_tram_2G', models.IntegerField(null=True, blank=True)),
                ('so_luong_tram_3G', models.IntegerField(null=True, blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_diaban_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoiTac',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=80)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True, blank=True)),
                ('Don_vi', models.CharField(max_length=80, null=True, verbose_name='\u0110\u01a1n V\u1ecb', blank=True)),
                ('So_dien_thoai', models.CharField(max_length=80, null=True, verbose_name='S\u1ed1 \u0111i\u1ec7n tho\u1ea1i', blank=True)),
                ('Nam_sinh', models.CharField(max_length=80, null=True, verbose_name='N\u0103m Sinh', blank=True)),
                ('email', models.CharField(max_length=80, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=80, null=True, verbose_name='Ghi ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_doitac_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_doitac_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DuAn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=150)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True)),
                ('ghi_chu', models.CharField(max_length=1330, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('type_2G_or_3G', models.CharField(max_length=2, blank=True)),
                ('thoi_diem_bat_dau', models.DateTimeField(null=True, verbose_name='th\u1eddi \u0111i\u1ec3m b\u1eaft \u0111\u1ea7u', blank=True)),
                ('thoi_diem_ket_thuc', models.DateTimeField(null=True, verbose_name='th\u1eddi \u0111i\u1ec3m k\u1ebft th\xfac', blank=True)),
                ('is_duoc_tao_truoc', models.BooleanField(default=False, verbose_name='Kh\xf4ng cho ph\xe9p s\u1eeda field Name')),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('doi_tac_du_an', models.ManyToManyField(to='rnoc.DoiTac', verbose_name='\u0110\u1ed1i t\xe1c d\u1ef1 \xe1n', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_duan_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_duan_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('modal_name', models.CharField(max_length=50)),
                ('edited_object_id', models.IntegerField()),
                ('ly_do_sua', models.CharField(max_length=250, null=True, blank=True)),
                ('edit_datetime', models.DateTimeField(null=True, blank=True)),
                ('thanh_vien', models.ForeignKey(verbose_name='Th\xe0nh vi\xean s\u1eeda', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultLibrary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=100)),
                ('diversity', models.CharField(max_length=10, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_FaultLibrary_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_FaultLibrary_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lenh',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('command', models.CharField(max_length=5000)),
                ('Name', models.CharField(unique=True, max_length=200)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True, blank=True)),
                ('ghi_chu_lenh', models.CharField(max_length=200, null=True, verbose_name='Ghi ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_Lenh_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_Lenh_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mll',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object', models.CharField(max_length=50, verbose_name='\u0110\u1ed1i t\u01b0\u1ee3ng')),
                ('site_name', models.CharField(max_length=50, null=True, verbose_name='Site name', blank=True)),
                ('nguyen_nhan_cu_the', models.CharField(max_length=1000, null=True, verbose_name='Nguy\xean nh\xe2n c\u1ee5 th\u1ec3', blank=True)),
                ('ung_cuu', models.BooleanField(default=False, verbose_name='\u01b0/c')),
                ('gio_mat', models.DateTimeField(verbose_name='Gi\u1edd m\u1ea5t', blank=True)),
                ('gio_tot', models.DateTimeField(null=True, verbose_name='Gi\u1edd t\u1ed1t', blank=True)),
                ('giao_ca', models.BooleanField(default=False, verbose_name='g/ca')),
                ('nghiem_trong', models.IntegerField(null=True, verbose_name='N/tr\u1ecdng', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('ca_truc', models.ForeignKey(verbose_name='Ca tr\u1ef1c', blank=True, to='rnoc.CaTruc', null=True)),
                ('du_an', models.ForeignKey(related_name='DuAns', verbose_name='D\u1ef1 \xe1n', blank=True, to='rnoc.DuAn', null=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_mll_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_mlll_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSC',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=50)),
                ('ghi_chu', models.CharField(max_length=5000, null=True, verbose_name='Ghi ch\xfa', blank=True)),
                ('msc_or_sgsn', models.CharField(max_length=20, null=True, verbose_name='MSC hay SGSN', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_MSC_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_MSC_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NguyenNhan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=150)),
                ('Name_khong_dau', models.CharField(max_length=150, null=True)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_NguyenNhan_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_NguyenNhan_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhuongXa',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='QuanHuyen',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('query_string', models.CharField(max_length=200, null=True, blank=True)),
                ('search_datetime', models.DateTimeField(null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=200, null=True, blank=True)),
                ('thanh_vien', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificProblem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object_name', models.CharField(max_length=200, null=True, blank=True)),
                ('fault', models.ForeignKey(blank=True, to='rnoc.FaultLibrary', null=True)),
                ('mll', models.ForeignKey(related_name='specific_problems', to='rnoc.Mll')),
            ],
        ),
        migrations.CreateModel(
            name='SuCo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=150)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_nguyennhan_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_nguyennhan_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TanSo2G',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TanSo3G',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ThaoTacLienQuan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=100)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('Name_khong_dau', models.CharField(max_length=100, null=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_ThaoTacLienQuan_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_ThaoTacLienQuan_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=20)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi ch\xfa', blank=True)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('is_duoc_tao_truoc', models.BooleanField(verbose_name='Kh\xf4ng cho ph\xe9p s\u1eeda field Name')),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('brand', models.ForeignKey(blank=True, to='rnoc.Brand', null=True)),
                ('bts_type', models.ForeignKey(blank=True, to='rnoc.BTSType', null=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_thietbi_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_thietbi_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=50)),
                ('Name_khong_dau', models.CharField(unique=True, max_length=50, verbose_name='Name kh\xf4ng d\u1ea5u', blank=True)),
                ('ma_tinh', models.CharField(unique=True, max_length=4, verbose_name='M\xe3 T\u1ec9nh')),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('so_luong_tram_2G', models.IntegerField(null=True, verbose_name='S\u1ed1 l\u01b0\u1ee3ng tr\u1ea1m 2G', blank=True)),
                ('so_luong_tram_3G', models.IntegerField(null=True, verbose_name='S\u1ed1 l\u01b0\u1ee3ng tr\u1ea1m 3G', blank=True)),
                ('tong_so_tram', models.IntegerField(null=True, verbose_name='T\u1ed5ng s\u1ed1 l\u01b0\u1ee3ng tr\u1ea1m', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('dia_ban', models.ForeignKey(verbose_name='\u0110\u1ecba B\xe0n', to='rnoc.DiaBan', null=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_Tinh_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TracNghiem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cau_hoi', models.CharField(unique=True, max_length=500)),
                ('is_multiple_choice', models.BooleanField(default=False)),
                ('dap_an', models.ManyToManyField(to='rnoc.DapAn')),
            ],
        ),
        migrations.CreateModel(
            name='Tram',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Site_Name_1', models.CharField(max_length=80, null=True)),
                ('Site_Name_2', models.CharField(max_length=80, null=True, blank=True)),
                ('ghi_chu_tram', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('import_ghi_chu', models.CharField(max_length=400, null=True, verbose_name='Ghi Ch\xfa import', blank=True)),
                ('dia_chi_3G', models.CharField(max_length=200, null=True, verbose_name='\u0110\u1ecba ch\u1ec9 3G', blank=True)),
                ('Nha_Tram', models.CharField(max_length=20, null=True, verbose_name='Nh\xe0 Tr\u1ea1m', blank=True)),
                ('Ma_Tram_DHTT', models.CharField(max_length=20, null=True, verbose_name='M\xe3 tr\u1ea1m \u0110HTT', blank=True)),
                ('dia_chi_3G_khong_dau', models.CharField(max_length=200, null=True, verbose_name='\u0110\u1ecba ch\u1ec9 3G khong dau', blank=True)),
                ('dia_chi_2G', models.CharField(max_length=200, null=True, verbose_name='\u0110\u1ecba ch\u1ec9 2G', blank=True)),
                ('dia_chi_2G_khong_dau', models.CharField(max_length=200, null=True, verbose_name='\u0110\u1ecba ch\u1ec9 2G khong dau', blank=True)),
                ('booster', models.CharField(max_length=80, null=True, blank=True)),
                ('Ngay_Phat_Song_2G', models.DateField(null=True, verbose_name='Ng\xe0y ph\xe1t s\xf3ng 2G', blank=True)),
                ('Site_ID_2G', models.CharField(max_length=80, null=True, blank=True)),
                ('Site_ID_2G_Number', models.CharField(max_length=100, null=True, blank=True)),
                ('LAC_2G', models.CharField(max_length=20, null=True, blank=True)),
                ('Cell_ID_2G', models.CharField(max_length=220, null=True, blank=True)),
                ('Long_2G', models.CharField(max_length=30, null=True, blank=True)),
                ('Lat_2G', models.CharField(max_length=30, null=True, blank=True)),
                ('active_2G', models.BooleanField(default=False, verbose_name='\u0110ang Active 2G')),
                ('TRX_DEF', models.CharField(max_length=50, null=True, blank=True)),
                ('TG_Text', models.CharField(max_length=150, null=True, blank=True)),
                ('TG', models.CharField(max_length=3, null=True, blank=True)),
                ('TG_1800', models.CharField(max_length=3, null=True, blank=True)),
                ('IUB_VLAN_ID_4G', models.CharField(max_length=4, null=True, blank=True)),
                ('IUB_SUBNET_PREFIX_4G', models.CharField(max_length=40, null=True, blank=True)),
                ('IUB_DEFAULT_ROUTER_4G', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('IUB_HOST_IP_4G', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('MUB_VLAN_ID_4G', models.CharField(max_length=4, null=True, blank=True)),
                ('MUB_SUBNET_PREFIX_4G', models.CharField(max_length=40, null=True, blank=True)),
                ('MUB_DEFAULT_ROUTER_4G', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('MUB_HOST_IP_4G', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('active_4G', models.BooleanField(default=False, verbose_name='\u0110ang Active 4G')),
                ('eNodeB_Name', models.CharField(max_length=40, null=True, blank=True)),
                ('eNodeB_ID_DEC', models.CharField(max_length=6, null=True, blank=True)),
                ('License_60W_Power', models.NullBooleanField()),
                ('U900', models.NullBooleanField()),
                ('Site_ID_3G', models.CharField(max_length=80, null=True, blank=True)),
                ('Ngay_Phat_Song_3G', models.DateField(null=True, verbose_name='Ng\xe0y ph\xe1t s\xf3ng 3G', blank=True)),
                ('Status', models.CharField(max_length=50, null=True, blank=True)),
                ('Project_Text', models.CharField(max_length=100, null=True, blank=True)),
                ('Trans', models.CharField(max_length=40, null=True, blank=True)),
                ('Port', models.CharField(max_length=40, null=True, blank=True)),
                ('IUB_VLAN_ID', models.CharField(max_length=4, null=True, blank=True)),
                ('IUB_SUBNET_PREFIX', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('IUB_DEFAULT_ROUTER', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('IUB_HOST_IP', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('MUB_VLAN_ID', models.CharField(max_length=4, null=True, blank=True)),
                ('MUB_SUBNET_PREFIX', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('MUB_DEFAULT_ROUTER', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('MUB_HOST_IP', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('Cell_1_Site_remote', models.CharField(max_length=40, null=True, verbose_name=b'Cell_1', blank=True)),
                ('Cell_2_Site_remote', models.CharField(max_length=40, null=True, verbose_name=b'Cell_2', blank=True)),
                ('Cell_3_Site_remote', models.CharField(max_length=40, null=True, verbose_name=b'Cell_3', blank=True)),
                ('Cell_4_Site_remote', models.CharField(max_length=40, null=True, verbose_name=b'Cell_4', blank=True)),
                ('Cell_5_Site_remote', models.CharField(max_length=40, null=True, verbose_name=b'Cell_5', blank=True)),
                ('Cell_6_Site_remote', models.CharField(max_length=40, null=True, verbose_name=b'Cell_6', blank=True)),
                ('Cell_7_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_8_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_9_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_K_U900_PSI', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_ID_3G', models.CharField(max_length=220, null=True, blank=True)),
                ('LAC_3G', models.CharField(max_length=10, null=True, blank=True)),
                ('Long_3G', models.CharField(max_length=30, null=True, blank=True)),
                ('Lat_3G', models.CharField(max_length=30, null=True, blank=True)),
                ('ntpServerIpAddressPrimary', models.CharField(max_length=20, null=True, blank=True)),
                ('ntpServerIpAddressSecondary', models.CharField(max_length=20, null=True, blank=True)),
                ('ntpServerIpAddress1', models.CharField(max_length=20, null=True, blank=True)),
                ('ntpServerIpAddress2', models.CharField(max_length=20, null=True, blank=True)),
                ('is_co_U900_rieng', models.NullBooleanField(default=False, verbose_name='Site 3G U2100 c\xf3 Site U900 ri\xeang')),
                ('is_co_U2100_rieng', models.NullBooleanField(default=False, verbose_name='Site 3G U900 c\xf3 Site U2100 ri\xeang')),
                ('active_3G', models.BooleanField(default=False, verbose_name='\u0110ang Active 3G')),
                ('ngay_gio_tao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('BSC_2G', models.ForeignKey(related_name='bscrnc_dot_Tram_BSC_2G_set', blank=True, to='rnoc.BSCRNC', null=True)),
                ('Cabinet', models.ForeignKey(related_name='Tramcuathietbis', verbose_name='Thi\u1ebft b\u1ecb 3G', blank=True, to='rnoc.ThietBi', null=True)),
                ('RNC', models.ForeignKey(blank=True, to='rnoc.BSCRNC', null=True)),
                ('Site_type', models.ForeignKey(to='rnoc.SiteType')),
            ],
        ),
        migrations.CreateModel(
            name='TrangThai',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=100)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('is_cap_nhap_gio_tot', models.BooleanField(default=False, verbose_name='Tr\u1ea1ng th\xe1i n\xe0y c\xf3 t\u1ef1 c\u1eadp nh\u1eadp gi\u1edd t\u1ed1t kh\xf4ng ?')),
                ('is_duoc_tao_truoc', models.BooleanField(default=False, verbose_name='Kh\xf4ng cho ph\xe9p s\u1eeda field Name')),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, null=True, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_trangthai_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_trangthai_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UPE',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=80)),
                ('tinh', models.ForeignKey(related_name='Tinh_dot_UPE_sets', to='rnoc.Tinh')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('so_dien_thoai', models.CharField(max_length=20, null=True, verbose_name='S\u1ed1 \u0111i\u1ec7n tho\u1ea1i', blank=True)),
                ('color_code', models.CharField(max_length=15, null=True, verbose_name='M\xe0u hi\u1ec3n th\u1ecb', blank=True)),
                ('khong_search_tu_dong', models.BooleanField(default=True, verbose_name='Kh\xf4ng search t\u1ef1 \u0111\u1ed9ng \u0111\u1ed1i v\u1edbi table MLL')),
                ('khong_search_tu_dong_tram', models.BooleanField(default=True, verbose_name='Kh\xf4ng search t\u1ef1 \u0111\u1ed9ng Tr\u1ea1m')),
                ('ca_truc', models.ForeignKey(verbose_name='B\u1ea1n \u0111ang tr\u1ef1c ca n\xe0o?', blank=True, to='rnoc.CaTruc', null=True)),
                ('loc_ca', models.ManyToManyField(related_name='catruc_dot_userprofile_dot_set', verbose_name='B\u1ea1n mu\u1ed1n hi\xean th\u1ecb ca n\xe0o?', to='rnoc.CaTruc', blank=True)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tram',
            name='UPE',
            field=models.ForeignKey(blank=True, to='rnoc.UPE', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='brand_2G',
            field=models.ForeignKey(blank=True, to='rnoc.Brand', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='brand_3G',
            field=models.ForeignKey(related_name='brand_3g_set_dot_tram', blank=True, to='rnoc.Brand', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='brand_4G',
            field=models.ForeignKey(related_name='brand_4g_set_dot_tram', blank=True, to='rnoc.Brand', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='cau_hinh_2G',
            field=models.ForeignKey(related_name='Tram_cau_hinh_2G', verbose_name='C\u1ea5u h\xecnh 2G', blank=True, to='rnoc.CauHinh', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='cau_hinh_3G',
            field=models.ForeignKey(related_name='Tram_cau_hinh_3G', verbose_name='C\u1ea5u h\xecnh 3G', blank=True, to='rnoc.CauHinh', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='du_an',
            field=models.ManyToManyField(to='rnoc.DuAn', verbose_name='D\u1ef1 \xe1n', blank=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='eNodeB_Type',
            field=models.ForeignKey(related_name='ThietBi_of_eNodeB', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='nguoi_sua_cuoi_cung',
            field=models.ForeignKey(related_name='user_nguoi_sua_dot_tram_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='nguoi_tao',
            field=models.ForeignKey(related_name='user_nguoi_tao_dot_tram_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tram',
            name='nha_san_xuat_2G',
            field=models.ForeignKey(verbose_name='Thi\u1ebft b\u1ecb 2G', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='phuong_xa',
            field=models.ForeignKey(verbose_name='Ph\u01b0\u1eddng X\xe3', blank=True, to='rnoc.PhuongXa', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='quan_huyen',
            field=models.ForeignKey(verbose_name='Qu\u1eadn huy\u1ec7n', blank=True, to='rnoc.QuanHuyen', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='tan_so_2G',
            field=models.ForeignKey(blank=True, to='rnoc.TanSo2G', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='tinh',
            field=models.ForeignKey(related_name='tinh_dot_tram_set', verbose_name='T\u1ec9nh', blank=True, to='rnoc.Tinh', null=True),
        ),
        migrations.AddField(
            model_name='quanhuyen',
            name='tinh',
            field=models.ForeignKey(related_name='Tinh_dot_quan_huyen_sets', to='rnoc.Tinh'),
        ),
        migrations.AddField(
            model_name='phuongxa',
            name='quan_huyen',
            field=models.ForeignKey(related_name='Quan_huyen_dot_phuong_xa_sets', to='rnoc.QuanHuyen'),
        ),
        migrations.AddField(
            model_name='phuongxa',
            name='tinh',
            field=models.ForeignKey(related_name='Tinh_dot_phuong_xa_sets', to='rnoc.Tinh'),
        ),
        migrations.AddField(
            model_name='mll',
            name='nguyen_nhan',
            field=models.ForeignKey(related_name='mll_set_of_NguyenNhan', verbose_name='Nguy\xean nh\xe2n chung', blank=True, to='rnoc.NguyenNhan', null=True),
        ),
        migrations.AddField(
            model_name='mll',
            name='su_co',
            field=models.ForeignKey(related_name='Mlls', verbose_name='S\u1ef1 c\u1ed1/Event/C\xf4ng Vi\u1ec7c', blank=True, to='rnoc.SuCo', null=True),
        ),
        migrations.AddField(
            model_name='mll',
            name='thiet_bi',
            field=models.ForeignKey(verbose_name='Thi\u1ebft b\u1ecb', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='mll',
            name='trang_thai',
            field=models.ForeignKey(verbose_name='Tr\u1ea1ng th\xe1i', blank=True, to='rnoc.TrangThai', null=True),
        ),
        migrations.AddField(
            model_name='lenh',
            name='thiet_bi',
            field=models.ForeignKey(verbose_name='Thi\u1ebft b\u1ecb', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='thiet_bi_of_component',
            field=models.ForeignKey(verbose_name='Thi\u1ebft b\u1ecb', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='component_lien_quan',
            field=models.ManyToManyField(to='rnoc.Component', null=True, verbose_name='Component li\xean quan', blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='doi_tac',
            field=models.ForeignKey(related_name='Comments', verbose_name='\u0111\u1ed1i t\xe1c', blank=True, to='rnoc.DoiTac', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='lenh_lien_quan',
            field=models.ManyToManyField(to='rnoc.Lenh', verbose_name='L\u1ec7nh li\xean quan', blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='mll',
            field=models.ForeignKey(related_name='comments', blank=True, to='rnoc.Mll'),
        ),
        migrations.AddField(
            model_name='comment',
            name='nguoi_sua_cuoi_cung',
            field=models.ForeignKey(related_name='user_nguoi_sua_dot_comment_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='nguoi_tao',
            field=models.ForeignKey(related_name='user_nguoi_tao_dot_comment_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='thao_tac_lien_quan',
            field=models.ManyToManyField(to='rnoc.ThaoTacLienQuan', verbose_name='Thao t\xe1c', blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='trang_thai',
            field=models.ForeignKey(verbose_name='Tr\u1ea1ng th\xe1i', blank=True, to='rnoc.TrangThai'),
        ),
        migrations.AddField(
            model_name='bscrnc',
            name='MSC',
            field=models.ForeignKey(related_name='msc_dot_msc_set', verbose_name='MSC', blank=True, to='rnoc.MSC', null=True),
        ),
        migrations.AddField(
            model_name='bscrnc',
            name='SGSN',
            field=models.ForeignKey(related_name='msc_dot_sgsn_set', blank=True, to='rnoc.MSC', null=True),
        ),
        migrations.AddField(
            model_name='bscrnc',
            name='VI_TRI_RNC',
            field=models.ForeignKey(blank=True, to='rnoc.Tinh', null=True),
        ),
        migrations.AddField(
            model_name='bscrnc',
            name='brand',
            field=models.ForeignKey(blank=True, to='rnoc.Brand', null=True),
        ),
        migrations.AddField(
            model_name='bscrnc',
            name='nguoi_sua_cuoi_cung',
            field=models.ForeignKey(related_name='user_nguoi_sua_dot_BSCRNC_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='bscrnc',
            name='nguoi_tao',
            field=models.ForeignKey(related_name='user_nguoi_tao_dot_BSCRNC_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bcnoss',
            name='BSC_or_RNC',
            field=models.ForeignKey(blank=True, to='rnoc.BSCRNC', null=True),
        ),
        migrations.AddField(
            model_name='bcnoss',
            name='BTS_Type',
            field=models.ForeignKey(verbose_name='2G,3G or 4G', blank=True, to='rnoc.BTSType', null=True),
        ),
        migrations.AddField(
            model_name='bcnoss',
            name='BTS_thiet_bi',
            field=models.ForeignKey(verbose_name='Nh\xe0 s\u1ea3n xu\u1ea5t', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='bcnoss',
            name='tinh',
            field=models.ForeignKey(verbose_name='T\u1ec9nh', to='rnoc.Tinh'),
        ),
    ]
