# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rnoc', '0021_auto_20170109_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='trangthai',
            name='image',
            field=filebrowser.fields.FileBrowseField(max_length=400, null=True, verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='duan',
            name='ghi_chu',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ghi Ch\xfa'),
        ),
        migrations.AlterField(
            model_name='lenh',
            name='command',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mll',
            name='nguyen_nhan_cu_the',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nguy\xean nh\xe2n c\u1ee5 th\u1ec3'),
        ),
        migrations.AlterField(
            model_name='msc',
            name='ghi_chu',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ghi ch\xfa'),
        ),
        migrations.AlterField(
            model_name='trangthai',
            name='ghi_chu',
            field=tinymce_4.fields.TinyMCEModelField(blank=True, null=True, verbose_name='Ghi Ch\xfa'),
        ),
    ]
